workflows:
  stadiome-workflow:
    name: Stadiome Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Prepare project and build iOS & Android
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release --no-codesign
          flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/app/outputs/flutter-apk/*.apk