workflows:
  stadiome-workflow:
    name: Stadiome Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Force recreate project and build iOS
        script: |
          rm -rf ios android
          flutter create . --platforms=ios,android
          flutter pub get
          flutter build ios --release --no-codesign