// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlVLWeSc5REwmNyDAbZJNv1oDURUzJgCA',
    appId: '1:314031271627:web:fc84b6400b942f2d5ef54e',
    messagingSenderId: '314031271627',
    projectId: 'stadiome-1a15f',
    authDomain: 'stadiome-1a15f.firebaseapp.com',
    storageBucket: 'stadiome-1a15f.firebasestorage.app',
    measurementId: 'G-Z21V344V36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNMLxiyTOl71ozRHm86ywls8S6cpH4tOc',
    appId: '1:314031271627:android:c7025b62e94b86535ef54e',
    messagingSenderId: '314031271627',
    projectId: 'stadiome-1a15f',
    storageBucket: 'stadiome-1a15f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwfENJ6heeqlYPySyEuyVpdx_tyPfnXD0',
    appId: '1:314031271627:ios:745477fd2233d0095ef54e',
    messagingSenderId: '314031271627',
    projectId: 'stadiome-1a15f',
    storageBucket: 'stadiome-1a15f.firebasestorage.app',
    iosBundleId: 'com.example.stadiomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwfENJ6heeqlYPySyEuyVpdx_tyPfnXD0',
    appId: '1:314031271627:ios:745477fd2233d0095ef54e',
    messagingSenderId: '314031271627',
    projectId: 'stadiome-1a15f',
    storageBucket: 'stadiome-1a15f.firebasestorage.app',
    iosBundleId: 'com.example.stadiomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlVLWeSc5REwmNyDAbZJNv1oDURUzJgCA',
    appId: '1:314031271627:web:4be99f63cc08fefa5ef54e',
    messagingSenderId: '314031271627',
    projectId: 'stadiome-1a15f',
    authDomain: 'stadiome-1a15f.firebaseapp.com',
    storageBucket: 'stadiome-1a15f.firebasestorage.app',
    measurementId: 'G-EXNEQKV0HJ',
  );
}
